name: model-env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - numpy=1.21.0
  - pip=21.3.1
  - scikit-learn=1.0.0
  - scipy=1.7.1
  - numpy
  - pandas==1.3.0
  - pip:
    - azureml-defaults==1.51.0
    - applicationinsights
    - inference-schema[numpy-support]==1.5
    - joblib==1.2.0
